### ISSUE TITLE
Readme 에서 오타를 발견했어요!

### ISSUE THREAD

**Issue by jihyojeon** [junhoyeo/junhoyeo#5]
`**Software Enginner 🦄⚡️** at [@Alphaworks](https://github.com/alpha-dao)`
->
`**Software Engineer 🦄⚡️** at [@Alphaworks](https://github.com/alpha-dao)`

**Comment by junhoyeo** [comment]
헉ㅠ 꿈에도 몰랐네요 👍👍 꼼꼼히 봐주셔서 감사합니다!
